### PR TITLE
Add Python 3 Trove classifier ("Programming Language :: Python :: 3") to setup.py

### PR DESCRIPTION
**Pull request by msabramo**
This will let people and tools (e.g.: https://python3wos.appspot.com/) know that yolk is compatible with Python 3.

Should do a release to PyPI; it seems that the latest code in GitHub works with Python 3, but the last released version on PyPI ([0.4.3](http://pypi.python.org/pypi/yolk/0.4.3); released 2012-02-06) doesn't work with Python 3.

### CODE REVIEW

**Comment by cakebread** [comment]
Thanks, Marc. I'm going to try to do a release tonight.

**Comment by msabramo** [comment]
Let me know if you need help testing

**Comment by msabramo** [comment]
Looks like this got lost in the shuffle?

**Comment by msabramo** [comment]
Bump.

**Comment by msabramo** [comment]
Bump.

**Pull request closed without merging**
